import json
from pathlib import Path

import pytest
import yaml  # type: ignore[import-untyped]
from jsonschema import Draft202012Validator
from pydantic import ValidationError

from app.api.v1.platform import CertificationSubmission, ServiceCreate


ROOT = Path(__file__).resolve().parents[1]


def test_repository_manifest_matches_canonical_schema() -> None:
    schema = json.loads((ROOT / "contracts/platform/service.v1.schema.json").read_text())
    manifest = yaml.safe_load((ROOT / ".codestra/service.yaml").read_text())
    Draft202012Validator(schema).validate(manifest)


def test_catalog_rejects_ungoverned_repository() -> None:
    with pytest.raises(ValidationError):
        ServiceCreate.model_validate({
            "service_id": "example-api", "owner": "platform", "tenant_mode": "multi-tenant",
            "type": "api", "repository": "another-owner/example", "environments": ["staging"],
            "dependencies": [], "data_classification": "confidential",
            "slo_profile": "customer-api", "alert_profile": "business-critical",
        })


def test_certification_evidence_excludes_review_reason() -> None:
    evidence = {name: True for name in CertificationSubmission.model_fields if name != "reason"}
    submission = CertificationSubmission(reason="Evidence generated by immutable CI run 1234", **evidence)
    assert len(submission.evidence()) == 15
    assert all(submission.evidence().values())
